// SPDX-License-Identifier: MIT
// Code generated by MockGen. DO NOT EDIT.
// Source: ../gitea_credentials.go
//
// Generated by this command:
//
//	mockgen -package mock -destination=gitea_credentials.go -source=../gitea_credentials.go GiteaCredentialsClient
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	credentials "github.com/cloudbase/garm/client/credentials"
	gomock "go.uber.org/mock/gomock"
)

// MockGiteaCredentialsClient is a mock of GiteaCredentialsClient interface.
type MockGiteaCredentialsClient struct {
	ctrl     *gomock.Controller
	recorder *MockGiteaCredentialsClientMockRecorder
}

// MockGiteaCredentialsClientMockRecorder is the mock recorder for MockGiteaCredentialsClient.
type MockGiteaCredentialsClientMockRecorder struct {
	mock *MockGiteaCredentialsClient
}

// NewMockGiteaCredentialsClient creates a new mock instance.
func NewMockGiteaCredentialsClient(ctrl *gomock.Controller) *MockGiteaCredentialsClient {
	mock := &MockGiteaCredentialsClient{ctrl: ctrl}
	mock.recorder = &MockGiteaCredentialsClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGiteaCredentialsClient) EXPECT() *MockGiteaCredentialsClientMockRecorder {
	return m.recorder
}

// CreateGiteaCredentials mocks base method.
func (m *MockGiteaCredentialsClient) CreateGiteaCredentials(params *credentials.CreateGiteaCredentialsParams) (*credentials.CreateGiteaCredentialsOK, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateGiteaCredentials", params)
	ret0, _ := ret[0].(*credentials.CreateGiteaCredentialsOK)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateGiteaCredentials indicates an expected call of CreateGiteaCredentials.
func (mr *MockGiteaCredentialsClientMockRecorder) CreateGiteaCredentials(params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateGiteaCredentials", reflect.TypeOf((*MockGiteaCredentialsClient)(nil).CreateGiteaCredentials), params)
}

// DeleteGiteaCredentials mocks base method.
func (m *MockGiteaCredentialsClient) DeleteGiteaCredentials(params *credentials.DeleteGiteaCredentialsParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteGiteaCredentials", params)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteGiteaCredentials indicates an expected call of DeleteGiteaCredentials.
func (mr *MockGiteaCredentialsClientMockRecorder) DeleteGiteaCredentials(params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteGiteaCredentials", reflect.TypeOf((*MockGiteaCredentialsClient)(nil).DeleteGiteaCredentials), params)
}

// GetGiteaCredentials mocks base method.
func (m *MockGiteaCredentialsClient) GetGiteaCredentials(params *credentials.GetGiteaCredentialsParams) (*credentials.GetGiteaCredentialsOK, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGiteaCredentials", params)
	ret0, _ := ret[0].(*credentials.GetGiteaCredentialsOK)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGiteaCredentials indicates an expected call of GetGiteaCredentials.
func (mr *MockGiteaCredentialsClientMockRecorder) GetGiteaCredentials(params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGiteaCredentials", reflect.TypeOf((*MockGiteaCredentialsClient)(nil).GetGiteaCredentials), params)
}

// ListGiteaCredentials mocks base method.
func (m *MockGiteaCredentialsClient) ListGiteaCredentials(params *credentials.ListGiteaCredentialsParams) (*credentials.ListGiteaCredentialsOK, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListGiteaCredentials", params)
	ret0, _ := ret[0].(*credentials.ListGiteaCredentialsOK)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListGiteaCredentials indicates an expected call of ListGiteaCredentials.
func (mr *MockGiteaCredentialsClientMockRecorder) ListGiteaCredentials(params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListGiteaCredentials", reflect.TypeOf((*MockGiteaCredentialsClient)(nil).ListGiteaCredentials), params)
}

// UpdateGiteaCredentials mocks base method.
func (m *MockGiteaCredentialsClient) UpdateGiteaCredentials(params *credentials.UpdateGiteaCredentialsParams) (*credentials.UpdateGiteaCredentialsOK, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateGiteaCredentials", params)
	ret0, _ := ret[0].(*credentials.UpdateGiteaCredentialsOK)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateGiteaCredentials indicates an expected call of UpdateGiteaCredentials.
func (mr *MockGiteaCredentialsClientMockRecorder) UpdateGiteaCredentials(params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateGiteaCredentials", reflect.TypeOf((*MockGiteaCredentialsClient)(nil).UpdateGiteaCredentials), params)
}
