// SPDX-License-Identifier: MIT
// Code generated by MockGen. DO NOT EDIT.
// Source: ../gitea_endpoint.go
//
// Generated by this command:
//
//	mockgen -package mock -destination=gitea_endpoint.go -source=../gitea_endpoint.go GiteaEndpointClient
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	endpoints "github.com/cloudbase/garm/client/endpoints"
	gomock "go.uber.org/mock/gomock"
)

// MockGiteaEndpointClient is a mock of GiteaEndpointClient interface.
type MockGiteaEndpointClient struct {
	ctrl     *gomock.Controller
	recorder *MockGiteaEndpointClientMockRecorder
}

// MockGiteaEndpointClientMockRecorder is the mock recorder for MockGiteaEndpointClient.
type MockGiteaEndpointClientMockRecorder struct {
	mock *MockGiteaEndpointClient
}

// NewMockGiteaEndpointClient creates a new mock instance.
func NewMockGiteaEndpointClient(ctrl *gomock.Controller) *MockGiteaEndpointClient {
	mock := &MockGiteaEndpointClient{ctrl: ctrl}
	mock.recorder = &MockGiteaEndpointClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGiteaEndpointClient) EXPECT() *MockGiteaEndpointClientMockRecorder {
	return m.recorder
}

// CreateGiteaEndpoint mocks base method.
func (m *MockGiteaEndpointClient) CreateGiteaEndpoint(params *endpoints.CreateGiteaEndpointParams) (*endpoints.CreateGiteaEndpointOK, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateGiteaEndpoint", params)
	ret0, _ := ret[0].(*endpoints.CreateGiteaEndpointOK)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateGiteaEndpoint indicates an expected call of CreateGiteaEndpoint.
func (mr *MockGiteaEndpointClientMockRecorder) CreateGiteaEndpoint(params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateGiteaEndpoint", reflect.TypeOf((*MockGiteaEndpointClient)(nil).CreateGiteaEndpoint), params)
}

// DeleteGiteaEndpoint mocks base method.
func (m *MockGiteaEndpointClient) DeleteGiteaEndpoint(params *endpoints.DeleteGiteaEndpointParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteGiteaEndpoint", params)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteGiteaEndpoint indicates an expected call of DeleteGiteaEndpoint.
func (mr *MockGiteaEndpointClientMockRecorder) DeleteGiteaEndpoint(params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteGiteaEndpoint", reflect.TypeOf((*MockGiteaEndpointClient)(nil).DeleteGiteaEndpoint), params)
}

// GetGiteaEndpoint mocks base method.
func (m *MockGiteaEndpointClient) GetGiteaEndpoint(params *endpoints.GetGiteaEndpointParams) (*endpoints.GetGiteaEndpointOK, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGiteaEndpoint", params)
	ret0, _ := ret[0].(*endpoints.GetGiteaEndpointOK)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGiteaEndpoint indicates an expected call of GetGiteaEndpoint.
func (mr *MockGiteaEndpointClientMockRecorder) GetGiteaEndpoint(params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGiteaEndpoint", reflect.TypeOf((*MockGiteaEndpointClient)(nil).GetGiteaEndpoint), params)
}

// ListGiteaEndpoints mocks base method.
func (m *MockGiteaEndpointClient) ListGiteaEndpoints(params *endpoints.ListGiteaEndpointsParams) (*endpoints.ListGiteaEndpointsOK, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListGiteaEndpoints", params)
	ret0, _ := ret[0].(*endpoints.ListGiteaEndpointsOK)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListGiteaEndpoints indicates an expected call of ListGiteaEndpoints.
func (mr *MockGiteaEndpointClientMockRecorder) ListGiteaEndpoints(params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListGiteaEndpoints", reflect.TypeOf((*MockGiteaEndpointClient)(nil).ListGiteaEndpoints), params)
}

// UpdateGiteaEndpoint mocks base method.
func (m *MockGiteaEndpointClient) UpdateGiteaEndpoint(params *endpoints.UpdateGiteaEndpointParams) (*endpoints.UpdateGiteaEndpointOK, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateGiteaEndpoint", params)
	ret0, _ := ret[0].(*endpoints.UpdateGiteaEndpointOK)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateGiteaEndpoint indicates an expected call of UpdateGiteaEndpoint.
func (mr *MockGiteaEndpointClientMockRecorder) UpdateGiteaEndpoint(params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateGiteaEndpoint", reflect.TypeOf((*MockGiteaEndpointClient)(nil).UpdateGiteaEndpoint), params)
}
