// SPDX-License-Identifier: MIT
// Code generated by MockGen. DO NOT EDIT.
// Source: ../scaleset.go
//
// Generated by this command:
//
//	mockgen -package mock -destination=scaleset.go -source=../scaleset.go ScaleSetClient
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	enterprises "github.com/cloudbase/garm/client/enterprises"
	organizations "github.com/cloudbase/garm/client/organizations"
	repositories "github.com/cloudbase/garm/client/repositories"
	scalesets "github.com/cloudbase/garm/client/scalesets"
	gomock "go.uber.org/mock/gomock"
)

// MockScaleSetClient is a mock of ScaleSetClient interface.
type MockScaleSetClient struct {
	ctrl     *gomock.Controller
	recorder *MockScaleSetClientMockRecorder
}

// MockScaleSetClientMockRecorder is the mock recorder for MockScaleSetClient.
type MockScaleSetClientMockRecorder struct {
	mock *MockScaleSetClient
}

// NewMockScaleSetClient creates a new mock instance.
func NewMockScaleSetClient(ctrl *gomock.Controller) *MockScaleSetClient {
	mock := &MockScaleSetClient{ctrl: ctrl}
	mock.recorder = &MockScaleSetClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockScaleSetClient) EXPECT() *MockScaleSetClientMockRecorder {
	return m.recorder
}

// CreateEnterpriseScaleSet mocks base method.
func (m *MockScaleSetClient) CreateEnterpriseScaleSet(param *enterprises.CreateEnterpriseScaleSetParams) (*enterprises.CreateEnterpriseScaleSetOK, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateEnterpriseScaleSet", param)
	ret0, _ := ret[0].(*enterprises.CreateEnterpriseScaleSetOK)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateEnterpriseScaleSet indicates an expected call of CreateEnterpriseScaleSet.
func (mr *MockScaleSetClientMockRecorder) CreateEnterpriseScaleSet(param any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateEnterpriseScaleSet", reflect.TypeOf((*MockScaleSetClient)(nil).CreateEnterpriseScaleSet), param)
}

// CreateOrgScaleSet mocks base method.
func (m *MockScaleSetClient) CreateOrgScaleSet(param *organizations.CreateOrgScaleSetParams) (*organizations.CreateOrgScaleSetOK, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrgScaleSet", param)
	ret0, _ := ret[0].(*organizations.CreateOrgScaleSetOK)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOrgScaleSet indicates an expected call of CreateOrgScaleSet.
func (mr *MockScaleSetClientMockRecorder) CreateOrgScaleSet(param any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrgScaleSet", reflect.TypeOf((*MockScaleSetClient)(nil).CreateOrgScaleSet), param)
}

// CreateRepoScaleSet mocks base method.
func (m *MockScaleSetClient) CreateRepoScaleSet(param *repositories.CreateRepoScaleSetParams) (*repositories.CreateRepoScaleSetOK, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRepoScaleSet", param)
	ret0, _ := ret[0].(*repositories.CreateRepoScaleSetOK)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRepoScaleSet indicates an expected call of CreateRepoScaleSet.
func (mr *MockScaleSetClientMockRecorder) CreateRepoScaleSet(param any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRepoScaleSet", reflect.TypeOf((*MockScaleSetClient)(nil).CreateRepoScaleSet), param)
}

// DeleteScaleSet mocks base method.
func (m *MockScaleSetClient) DeleteScaleSet(param *scalesets.DeleteScaleSetParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteScaleSet", param)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteScaleSet indicates an expected call of DeleteScaleSet.
func (mr *MockScaleSetClientMockRecorder) DeleteScaleSet(param any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteScaleSet", reflect.TypeOf((*MockScaleSetClient)(nil).DeleteScaleSet), param)
}

// GetScaleSet mocks base method.
func (m *MockScaleSetClient) GetScaleSet(param *scalesets.GetScaleSetParams) (*scalesets.GetScaleSetOK, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetScaleSet", param)
	ret0, _ := ret[0].(*scalesets.GetScaleSetOK)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetScaleSet indicates an expected call of GetScaleSet.
func (mr *MockScaleSetClientMockRecorder) GetScaleSet(param any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetScaleSet", reflect.TypeOf((*MockScaleSetClient)(nil).GetScaleSet), param)
}

// ListScaleSets mocks base method.
func (m *MockScaleSetClient) ListScaleSets(param *scalesets.ListScalesetsParams) (*scalesets.ListScalesetsOK, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListScaleSets", param)
	ret0, _ := ret[0].(*scalesets.ListScalesetsOK)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListScaleSets indicates an expected call of ListScaleSets.
func (mr *MockScaleSetClientMockRecorder) ListScaleSets(param any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListScaleSets", reflect.TypeOf((*MockScaleSetClient)(nil).ListScaleSets), param)
}

// UpdateScaleSet mocks base method.
func (m *MockScaleSetClient) UpdateScaleSet(param *scalesets.UpdateScaleSetParams) (*scalesets.UpdateScaleSetOK, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateScaleSet", param)
	ret0, _ := ret[0].(*scalesets.UpdateScaleSetOK)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateScaleSet indicates an expected call of UpdateScaleSet.
func (mr *MockScaleSetClientMockRecorder) UpdateScaleSet(param any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateScaleSet", reflect.TypeOf((*MockScaleSetClient)(nil).UpdateScaleSet), param)
}
