// SPDX-License-Identifier: MIT
// Code generated by MockGen. DO NOT EDIT.
// Source: ../template.go
//
// Generated by this command:
//
//	mockgen -package mock -destination=template.go -source=../template.go TemplateClient
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	templates "github.com/cloudbase/garm/client/templates"
	gomock "go.uber.org/mock/gomock"
)

// MockTemplateClient is a mock of TemplateClient interface.
type MockTemplateClient struct {
	ctrl     *gomock.Controller
	recorder *MockTemplateClientMockRecorder
}

// MockTemplateClientMockRecorder is the mock recorder for MockTemplateClient.
type MockTemplateClientMockRecorder struct {
	mock *MockTemplateClient
}

// NewMockTemplateClient creates a new mock instance.
func NewMockTemplateClient(ctrl *gomock.Controller) *MockTemplateClient {
	mock := &MockTemplateClient{ctrl: ctrl}
	mock.recorder = &MockTemplateClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTemplateClient) EXPECT() *MockTemplateClientMockRecorder {
	return m.recorder
}

// CreateTemplate mocks base method.
func (m *MockTemplateClient) CreateTemplate(params *templates.CreateTemplateParams) (*templates.CreateTemplateOK, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTemplate", params)
	ret0, _ := ret[0].(*templates.CreateTemplateOK)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTemplate indicates an expected call of CreateTemplate.
func (mr *MockTemplateClientMockRecorder) CreateTemplate(params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTemplate", reflect.TypeOf((*MockTemplateClient)(nil).CreateTemplate), params)
}

// DeleteTemplate mocks base method.
func (m *MockTemplateClient) DeleteTemplate(params *templates.DeleteTemplateParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTemplate", params)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTemplate indicates an expected call of DeleteTemplate.
func (mr *MockTemplateClientMockRecorder) DeleteTemplate(params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTemplate", reflect.TypeOf((*MockTemplateClient)(nil).DeleteTemplate), params)
}

// GetTemplate mocks base method.
func (m *MockTemplateClient) GetTemplate(params *templates.GetTemplateParams) (*templates.GetTemplateOK, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTemplate", params)
	ret0, _ := ret[0].(*templates.GetTemplateOK)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTemplate indicates an expected call of GetTemplate.
func (mr *MockTemplateClientMockRecorder) GetTemplate(params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTemplate", reflect.TypeOf((*MockTemplateClient)(nil).GetTemplate), params)
}

// ListTemplates mocks base method.
func (m *MockTemplateClient) ListTemplates(params *templates.ListTemplatesParams) (*templates.ListTemplatesOK, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTemplates", params)
	ret0, _ := ret[0].(*templates.ListTemplatesOK)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTemplates indicates an expected call of ListTemplates.
func (mr *MockTemplateClientMockRecorder) ListTemplates(params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTemplates", reflect.TypeOf((*MockTemplateClient)(nil).ListTemplates), params)
}

// UpdateTemplate mocks base method.
func (m *MockTemplateClient) UpdateTemplate(params *templates.UpdateTemplateParams) (*templates.UpdateTemplateOK, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTemplate", params)
	ret0, _ := ret[0].(*templates.UpdateTemplateOK)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateTemplate indicates an expected call of UpdateTemplate.
func (mr *MockTemplateClientMockRecorder) UpdateTemplate(params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTemplate", reflect.TypeOf((*MockTemplateClient)(nil).UpdateTemplate), params)
}
